Repository Step3-kakao-tech-campus/Team8_BE, pull requests merged in 2023-11, with the labels that each got.

#39 [9주차] 배포를 위한 설정 파일 수정 및 추가
  Dockerfile
  goorm.manifest
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
  k8s/redis.yaml
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
Labels: ✨ Feature, 🌏 Deploy

#40 [9주차] 배포환경, 테스트환경 별로 yml 설정
  wekiki/src/main/resources/application-local.yml
  wekiki/src/main/resources/application-prod.yml
  wekiki/src/main/resources/application.yml
Labels: ⚙️ Setting

#45 setting : yml 파일 수정
  wekiki/src/main/resources/application-local.yml
  wekiki/src/main/resources/application-prod.yml
  wekiki/src/main/resources/application.yml
Labels: ⚙️ Setting

#48 Refactor: 내 문서 기여 목록 응답DTO 1차 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/dto/GroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
Labels: 🔨 Refactor

#51 [10주차] 게시판 관련 API 리팩토링
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/config/RedisConfig.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/redis/RedisUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/repository/GroupMemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
Labels: ✨ Feature, 🔨 Refactor

#53 [10주차] 오류 수정 및 응답 DTO 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/controller/GroupRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/dto/GroupRequestDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/dto/GroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/repository/GroupJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/service/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/service/InvitationService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/ReportJPARepository.java
Labels: 🔨 Refactor, 🐞 BugFix

#59 [10주차] 그룹멤버 객체 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/domain/Group.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/domain/GroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/domain/member/ActiveGroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/domain/member/InactiveGroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/dto/GroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/repository/GroupMemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/service/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/Member.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/ReportJPARepository.java
Labels: 🔨 Refactor, 🐞 BugFix

#64 [10주차] Cascade 전략 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
Labels: 🐞 BugFix

#66 [10주차] 그룹 탈퇴 시 닉네임 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/domain/GroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/service/GroupService.java
Labels: 🔨 Refactor

#71 [10주차] 로깅 + 포스트 부분 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
Labels: ✨ Feature, 🔨 Refactor

#76 [10주차] 배포 전 수정
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/service/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberService.java
Labels: 🔨 Refactor

#81 Refactor: ReadMe 파일 수정
  README.md
Labels: 📃 Docs

#82 Docs: README.md 수정
  README.md
Labels: 📃 Docs
