Repository Step3-kakao-tech-campus/Team8_BE, pull requests merged in 2023-10, with the labels that each got.

#5 페이지 생성, 좋아요, 싫어요 API 구현
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/ApiUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/Page.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
Labels: ✨ Feature

#12 인증 관련 기능 구현
  wekiki/build.gradle
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/config/RedisConfig.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/config/SecurityConfig.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/GlobalExceptionHandler.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception400.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception401.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception403.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception404.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception500.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/jwt/JWTTokenFilter.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/jwt/JWTTokenProvider.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/CustomUserDetail.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/RedisUtility.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/SecurityUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/Authority.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/Member.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberService.java
  wekiki/src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#13 그룹 관련 기본 기능 구현
  wekiki/build.gradle
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/Group.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupType.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/requestDTO/CreateUnOfficialGroupRequestDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/requestDTO/JoinGroupRequestDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/requestDTO/UpdateMyGroupPageDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/CreateUnOfficialGroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/MyGroupInfoResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchGroupDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchGroupInfoDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/ActiveGroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/GroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/GroupMemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/InactiveGroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/unOfficialGroup/closedGroup/UnOfficialClosedGroup.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
Labels: ✨ Feature, 🔨 Refactor

#15 5주차 기능 구현
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/ApplicationException.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/ErrorCode.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/GlobalControllerAdvice.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/ApiUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
Labels: ✨ Feature

#18 배포를 위한 에러 해결
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception400.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception401.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception403.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception404.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception500.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/CustomUserDetail.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/SecurityUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/Member.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
Labels: 🌏 Deploy, 🐞 BugFix

#21 6주차 기능 구현
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception400.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception401.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception403.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception404.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/error/exception/Exception500.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/ApplicationException.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/ErrorCode.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/GlobalControllerAdvice.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/ApiUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/IndexUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/GroupMemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
Labels: ✨ Feature

#23 6주차 기능 구현
  wekiki/build.gradle
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/GetInvitationLinkResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/MyGroupInfoResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchGroupDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchOfficialGroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchUnOfficialGroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/ValidateInvitationResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/invitation/Invitation.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/unOfficialGroup/closedGroup/UnOfficialClosedGroup.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
Labels: ✨ Feature

#28 예외 처리 및 초대 링크 임시 구현
  wekiki/build.gradle
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/config/RedisConfig.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/MyGroupHistoryResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/MyGroupInfoResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/invitation/Invitation.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/GroupMemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/unOfficialGroup/closedGroup/UnOfficialClosedGroup.java
Labels: 🔨 Refactor, 🐞 BugFix

#26 부산대_8조_위키키_6주차
  wekiki/build.gradle
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/ApplicationException.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/ErrorCode.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/errors/GlobalControllerAdvice.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/ApiUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/CORSFilter.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/CustomUserDetail.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/IndexUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/_core/utils/SecurityUtils.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/GroupService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/GetInvitationLinkResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/MyGroupInfoResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchGroupDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchOfficialGroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/SearchUnOfficialGroupResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/groupDTO/responseDTO/ValidateInvitationResponseDTO.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/invitation/Invitation.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/GroupMemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/unOfficialGroup/closedGroup/UnOfficialClosedGroup.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/Member.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/MemberService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
Labels: :books: Request Review

#29 7주차 기능 구현
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/ReportJPARepository.java
Labels: ✨ Feature

#33 [8주차] 양방향 매핑 구현
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/Group.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/group/member/GroupMember.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/HistoryJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/member/Member.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/report/Report.java
Labels: ✨ Feature, 🐞 BugFix

#36 [8주차] 양방향 매핑에 따른 API 수정
  wekiki/Dockerfile
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/Comment.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/comment/CommentService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/history/History.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfo.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoRequest.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageInfoResponse.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageJPARepository.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/page/PageService.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/Post.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostRestController.java
  wekiki/src/main/java/com/kakao/techcampus/wekiki/post/PostService.java
Labels: ✨ Feature
